# #
# # See https://kubernetes.io/docs/concepts/services-networking/ingress/
# #
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend-ingress
#   annotations:
#     # use the shared ingress-nginx
#     kubernetes.io/ingress.class: "gce"
# spec:
#   rules:
# #
# # Your ingress rules here
# # Copied from https://kubernetes.io/docs/concepts/services-networking/ingress/
#   - http:
#       paths:
#       - path: /*
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: rest-svc
#             port:
#               number: 5000
#               # serviceName: rest
#               # servicePort: 5000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  rules:
#
# Your ingress rules here
# Copied from https://kubernetes.io/docs/concepts/services-networking/ingress/
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rest-svc
            port:
              number: 5000